services:
  audiveris:
    build: ./sheet2mxl
    container_name: audiveris
    volumes:
      - ./data:/home/rhythmic/data
      - ./scripts:/home/rhythmic/scripts
  omnizart:
    image: mctlab/omnizart:latest
    command: tail -f /dev/null
    container_name: omnizart
  mid2mxl:
    build: ./mid2mxl
    container_name: mid2mxl
  mscore:
    build: ./mscore
    container_name: mscore