services:
  audiveris:
    build: ./sheet2mxl
    container_name: audiveris
    volumes:
      - ./data:/rhythmic/data
      - ./scripts:/rhythmic/scripts
  omnizart:
    image: mctlab/omnizart:latest
    container_name: omnizart
    command: bash /tmp/dockerCommand.sh
    volumes:
      - ./omnizart/dockerCommand.sh:/tmp/dockerCommand.sh
      - ./data:/rhythmic/data
      - ./scripts:/rhythmic/scripts
  mscore:
    build: ./mscore
    container_name: mscore
    volumes:
      - ./data:/rhythmic/data
      - ./scripts:/rhythmic/scripts